export type {
  Vehicle,
  VehicleImage,
  VehicleEnquiry,
  TestDriveBooking,
  FinanceApplication,
  TradeInSubmission,
  BodyType,
  Transmission,
  FuelType,
  DriveType,
  ImportStatus,
  Condition,
  VehicleStatus,
} from "./index";
